name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test --org=${{ secrets.SNYK_ORG }} --sarif > snyk-sarif2.json // Updated Sarif.json file
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Validate SARIF JSON
        id: validate_sarif
        run: |
          if jq empty snyk-sarif2.json; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload SARIF file
        if: steps.validate_sarif.outputs.valid == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-sarif2.json
